#!/usr/bin/env bash
HERE="$(dirname "$(readlink -f "${0}")")"
export APPDIR="$HERE"

source "$APPDIR/fixes.sh"
make_temp_libdir
link_libraries
echo "AILIBDIR=$AILIBDIR"
fix_libxcb_dri3
fix_stdlibcxx
fix_fontconfig
#exit

cd "$HERE"
cd usr
HERE="$(pwd)"

export PATH="${PATH}:/sbin:/usr/sbin"
export LD_LIBRARY_PATH="$AILIBDIR:/usr/lib:$LD_LIBRARY_PATH"
export XDG_DATA_DIRS="${HERE}/share/:${HERE}/share/mime/:${XDG_DATA_DIRS}"
export GTK_PATH="${HERE}/lib/gtk-2.0:${GTK_PATH}"
export PANGO_LIBDIR="${HERE}/lib"
export GCONV_PATH="${HERE}/lib/gconv"
export GDK_PIXBUF_MODULEDIR="${HERE}/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders"
export GDK_PIXBUF_MODULE_FILE="${HERE}/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache"

#if [[ -e /etc/fonts/fonts.conf ]]; then
#  export FONTCONFIG_PATH=/etc/fonts
#fi
#export FONTCONFIG_PATH="$HERE/etc/fonts/fonts.conf"


ldd "./bin/rawtherapee"
"./bin/rawtherapee.wrapper" "$@"
#valgrind --tool=callgrind --instr-atstart=no "./bin/rawtherapee" "$@"

rm -rf "$AILIBDIR"
