#!/usr/bin/env bash
HERE="$(dirname "$(readlink -f "${0}")")"
export APPDIR="$HERE"

#export APPIMAGE_CHECKRT_DEBUG=1

source "$APPDIR/apprun-helper.sh"
save_environment
make_temp_libdir
link_libraries
echo "AILIBDIR=$AILIBDIR"
fix_libxcb_dri3
fix_stdlibcxx
#fix_fontconfig
fix_library "libfontconfig"
fix_library "libfreetype"
#exit

#cd "$HERE"
#cd usr
#HERE="$(pwd)"

export PATH="${PATH}:/sbin:/usr/sbin"
export LD_LIBRARY_PATH="$AILIBDIR:/usr/lib:$LD_LIBRARY_PATH"
export XDG_DATA_DIRS="${APPDIR}/usr/share/:${APPDIR}/usr/share/mime/:${XDG_DATA_DIRS}"
export GTK_PATH="${APPDIR}/usr/lib/gtk-2.0:${GTK_PATH}"
export PANGO_LIBDIR="${APPDIR}/usr/lib"
export GCONV_PATH="${APPDIR}/usr/lib/gconv"
#export GDK_PIXBUF_MODULEDIR="${APPDIR}/usr/lib/gdk-pixbuf-2.0/loaders"
#export GDK_PIXBUF_MODULE_FILE="${APPDIR}/usr/lib/gdk-pixbuf-2.0/loaders.cache"
mkdir -p "$AILIBDIR/gdk-pixbuf-2.0"
cp "${APPDIR}/usr/lib/gdk-pixbuf-2.0/loaders.cache" "$AILIBDIR/gdk-pixbuf-2.0"
sed -i -e "s|LOADERSDIR|${APPDIR}/usr/lib/gdk-pixbuf-2.0/loaders|g" "$AILIBDIR/gdk-pixbuf-2.0/loaders.cache"
export GDK_PIXBUF_MODULE_FILE="$AILIBDIR/gdk-pixbuf-2.0/loaders.cache"

#if [[ -e /etc/fonts/fonts.conf ]]; then
#  export FONTCONFIG_PATH=/etc/fonts
#fi
#export FONTCONFIG_PATH="$HERE/etc/fonts/fonts.conf"


ldd "${APPDIR}/usr/bin/rawtherapee"
echo ""
echo "=========="
echo ""
ldd "${APPDIR}/usr/lib/gdk-pixbuf-2.0/loaders/libpixbufloader-svg.so"
echo ""
echo "=========="
echo ""
echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
find "$APPDIR" -name "librsvg*.so*"
/sbin/ldconfig -p | grep 'librsvg'
echo ""
echo "=========="
echo ""
if [ x"$1" = "x--cli" ]; then
	shift
	"${APPDIR}/usr/bin/rawtherapee-cli" "$@"
else
	LD_PRELOAD="${APPDIR}/usr/lib/exec_wrapper2.so" "${APPDIR}/usr/bin/rawtherapee.wrapper" "$@"
#valgrind --tool=callgrind --instr-atstart=no "./bin/rawtherapee" "$@"
fi

rm -rf "$AILIBDIR"
rm -f "$AIPENV"
